name: push-to-collibra-environment

dependencies:
  - python=3.8
  - pyyaml
  - pytest-flake8
  - requests
  - sqlalchemy=2.0.0
  - pandas=1.5.3
  - pyodbc
  - pip
  - PyInstaller
  - coverage
  - chardet