name: push-to-collibra-environment

dependencies:
  - python=3.11
  - pyyaml
  - pytest-flake8
  - requests
  - sqlalchemy == 2.0.0
  - pandas=1.3.0
  - pyodbc
  - pip
  - PyInstaller
  - coverage
  - chardet