name: push-to-collibra-environment

dependencies:
  - python=3.8
  - pyyaml
  - pytest-flake8
  - requests
  - sqlalchemy=1.4.4
  - pandas=1.3.0
  - pyodbc=4.0.32
  - pip
  - PyInstaller
  - coverage
  - chardet